BACKEND: virtual
W:
  QSCHEME: per-channel-symmetric
  QUANTIZER: 
    TYPE: lsq
    BIT: 4
A:
  QSCHEME: per-tensor-affine
  QUANTIZER:
    TYPE: lsq+
    BIT: 4
  OBSERVER:
    TYPE: MSE
    LAYOUT: NCHW
